name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: windows-2019
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/costaisnotavailable/spotimatch
            azure-pipeline-name: 'spotimatch-CI'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
